// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7pTKY32xtV9nHzPEXRuKpgRr0nwPQ2a8',
    appId: '1:916195052113:web:883ece3185c7f3c1744670',
    messagingSenderId: '916195052113',
    projectId: 'learn-to-fly-f4fc6',
    authDomain: 'learn-to-fly-f4fc6.firebaseapp.com',
    storageBucket: 'learn-to-fly-f4fc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASM7cc_WCP5gqDy5KDNn_Rh7TgcQxD2CM',
    appId: '1:916195052113:android:3d24fcaf4cbbed34744670',
    messagingSenderId: '916195052113',
    projectId: 'learn-to-fly-f4fc6',
    storageBucket: 'learn-to-fly-f4fc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCafMHJqafALgk1uqJwEWrbBB2n8uAYPjc',
    appId: '1:916195052113:ios:10f4f0cab7b50259744670',
    messagingSenderId: '916195052113',
    projectId: 'learn-to-fly-f4fc6',
    storageBucket: 'learn-to-fly-f4fc6.appspot.com',
    iosClientId: '916195052113-u81o5c66bvup6rnnj0cs4g133a8dp5sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalhealthtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCafMHJqafALgk1uqJwEWrbBB2n8uAYPjc',
    appId: '1:916195052113:ios:10f4f0cab7b50259744670',
    messagingSenderId: '916195052113',
    projectId: 'learn-to-fly-f4fc6',
    storageBucket: 'learn-to-fly-f4fc6.appspot.com',
    iosClientId: '916195052113-u81o5c66bvup6rnnj0cs4g133a8dp5sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalhealthtracker',
  );
}
